FROM python:3.12-alpine

ENV PYTHONUNBUFFERED=1

WORKDIR /app/

COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY ./src ./src

CMD ["fastapi", "run", "--workers", "1", "/app/src/main.py"]

