FROM python:3.12-alpine

ENV PYTHONUNBUFFERED=1

WORKDIR /app/

COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
RUN pip install debugpy

COPY ./src ./src
EXPOSE 5678

CMD ["sh", "-c", "python -m debugpy --listen 0.0.0.0:5678 -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"]

