# Use the official .NET SDK image for build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS debug

#install debugger for NET Core
RUN apt-get update
RUN apt-get install -y unzip
RUN curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l ~/vsdbg

WORKDIR /src

# Copy csproj and restore as distinct layers
COPY SimpleIdentityServer.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . .

RUN dotnet build -c Debug

ENTRYPOINT ["dotnet", "run"]
